export const UPDATE_POPUPSTATUS = "UPDATE_POPUPSTATUS";
export const UPDATE_AUTH_DATA = "UPDATE_AUTH_DATA";
export const UPDATE_ACCESS_TOKEN = "UPDATE_ACCESS_TOKEN";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_CHEF_DATA = "UPDATE_CHEF_DATA";